package com.example.demo.service.query;

public interface BrandCommerceQuery {
    String getTotalSoldItemEachCityEachBrandQuery = "SELECT a.brand, CASE WHEN a.shipping_province ILIKE '%jawa barat%' THEN 'Jawa Barat' WHEN a.shipping_province ILIKE '%dki jakarta%' THEN 'DKI Jakarta' WHEN a.shipping_province ILIKE '%banten%' THEN 'Banten' WHEN a.shipping_province ILIKE '%jawa tengah%' THEN 'Jawa Tengah' WHEN a.shipping_province ILIKE '%jawa timur%' THEN 'Jawa Timur' WHEN a.shipping_province ILIKE '%sumatera utara%' THEN 'Sumatera Utara' ELSE 'Other' END AS province, sum(qty) AS quantity FROM (SELECT brand, order_id, shipping_province FROM brand_commerce.order_shipping WHERE order_id in (SELECT order_id FROM brand_commerce.order_transaction_bc_naufal WHERE date_paid IS NOT NULL AND order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment'))) AS a INNER JOIN brand_commerce.order_product AS b ON a.order_id = b.order_id GROUP BY(a.brand, province)";
//    String getTotalSoldItemEachBrandQuery = "select brand, sum(qty) as quantity from brand_commerce.order_product where order_id in (select order_id from brand_commerce.order_transaction_bc_naufal where date_paid is not null and order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment')) group by brand";
//    String getTotalSoldItemEachMonthEachBrandQuery = "select a.brand, bulan, sum(qty) as quantity from brand_commerce.order_product as a inner join (select brand, order_id, extract(MONTH from date_paid) as bulan from brand_commerce.order_transaction_bc_naufal where date_paid is not null and extract(YEAR from date_paid) = %d and order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment') and brand in ('Wardah', 'Kahf', 'Emina')) as b on a.brand = b.brand and a.order_id = b.order_id group by (a.brand, bulan)";
//    String getTotalSoldItemEachYearEachBrandQuery = "select a.brand, tahun, sum(qty) as quantity from brand_commerce.order_product as a inner join (select brand, order_id, extract(YEAR from date_paid) as tahun from brand_commerce.order_transaction_bc_naufal where date_paid is not null and order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment')) as b on a.brand = b.brand and a.order_id = b.order_id group by (a.brand, tahun) order by (tahun) asc";

    // New Business Question
    String getTotalSoldItemTopTenProvinceQuery = "select shipping_province as provinsi, sum(qty) as total from brand_commerce.order_shipping as c inner join (SELECT a.order_id, b.qty FROM brand_commerce.order_transaction_bc_naufal as a inner join brand_commerce.order_product as b on a.order_id = b.order_id where a.date_paid is not null and a.order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment') and a.brand in ('Wardah', 'Kahf', 'Emina')) as d on c.order_id = d.order_id group by c.shipping_province order by sum(qty) desc limit 10";
    String getTotalSoldItemEachBrandQuery = "select a.brand, sum(qty) as quantity from brand_commerce.order_product as a inner join (select brand, order_id from brand_commerce.order_transaction_bc_naufal where date_paid is not null and order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment') and brand in ('Wardah', 'Kahf', 'Emina')) as b on a.brand = b.brand and a.order_id = b.order_id group by (a.brand)";
    String getTotalSoldItemEachMonthEachBrandQuery = "select a.brand, bulan, sum(qty) as quantity from brand_commerce.order_product as a inner join (select brand, order_id, extract(MONTH from date_paid) as bulan from brand_commerce.order_transaction_bc_naufal where date_paid is not null and extract(YEAR from date_paid) = %d and order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment') and brand in ('Wardah', 'Kahf', 'Emina')) as b on a.brand = b.brand and a.order_id = b.order_id group by (a.brand, bulan) order by (a.brand, bulan)";
    String getTotalSoldItemEachYearEachBrandQuery = "select a.brand, tahun, sum(qty) as quantity from brand_commerce.order_product as a inner join (select brand, order_id, extract(YEAR from date_paid) as tahun from brand_commerce.order_transaction_bc_naufal where date_paid is not null and order_status in ('wc-closed', 'accepted', 'Completed', 'completed', 'wc-completed', 'Waiting Payment', 'Under Shipment') and brand in ('Wardah', 'Kahf', 'Emina')) as b on a.brand = b.brand and a.order_id = b.order_id group by (a.brand, tahun) order by (tahun) asc";
}
