package com.example.demo.service.query;

public interface ShopeeQuery {
    String getTotalSoldItemEachCityEachBrandQuery = "SELECT shopid AS brand, province, sum(qty_purchased) AS quantity FROM shopee.income_item_detail AS a INNER JOIN (SELECT ordersn, shopid, CASE WHEN recipient_province ILIKE '%jawa barat%' THEN 'Jawa Barat' WHEN recipient_province ILIKE '%dki jakarta%' THEN 'DKI Jakarta' WHEN recipient_province ILIKE '%banten%' THEN 'Banten' WHEN recipient_province ILIKE '%jawa tengah%' THEN 'Jawa Tengah' WHEN recipient_province ILIKE '%jawa timur%' THEN 'Jawa Timur' WHEN recipient_province ILIKE '%sumatera utara%' THEN 'Sumatera Utara' ELSE 'Other' END AS province FROM shopee.order_transaction_shopee_naufal WHERE pay_time IS NOT NULL AND shopid in (59763733, 575053680, 637555425, 63983008, 326487418, 524963178, 63984475, 401724234, 652866307, 625116419) AND order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) AS b ON a.ordersn = b.ordersn GROUP BY(brand, province)";
//    String getTotalSoldItemEachBrandQuery = "select shopid as brand, sum(qty_purchased) as quantity from shopee.income_item_detail as a inner join (select ordersn, shopid from shopee.\"order\" where pay_time is not null and shopid in (59763733, 575053680, 637555425, 63983008, 326487418, 524963178, 63984475, 401724234, 652866307, 625116419) and order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) as b on a.ordersn = b.ordersn group by brand";
//    String getTotalSoldItemEachMonthEachBrandQuery = "select shopid as brand, extract(MONTH from pay_time) as bulan, sum(qty_purchased) as quantity from shopee.income_item_detail as a inner join (select ordersn, shopid, pay_time from shopee.\"order\" where pay_time is not null and extract(YEAR from pay_time) = %d and shopid in (59763733, 575053680, 637555425, 63983008, 326487418, 524963178, 63984475, 401724234, 652866307, 625116419) and order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) as b on a.ordersn = b.ordersn group by(brand, bulan)";
//    String getTotalSoldItemEachYearEachBrandQuery = "select shopid as brand, extract(YEAR from pay_time) as tahun, sum(qty_purchased) as quantity from shopee.income_item_detail as a inner join (select ordersn, shopid, pay_time from shopee.\"order\" where pay_time is not null and shopid in (59763733, 575053680, 637555425, 63983008, 326487418, 524963178, 63984475, 401724234, 652866307, 625116419) and order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) as b on a.ordersn = b.ordersn group by(brand, tahun) order by (tahun) asc";

    // New Business Question
    String getTotalSoldItemTopTenProvinceQuery = "select a.recipient_province as provinsi, sum(qty_purchased) as total from shopee.order_transaction_shopee_naufal as a inner join shopee.income_item_detail as b on a.ordersn = b.ordersn WHERE a.pay_time IS NOT NULL AND a.shopid in (59763733, 63983008, 326487418) AND a.order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE') group by a.recipient_province order by sum(qty_purchased) desc limit 10";
    String getTotalSoldItemEachBrandQuery = "select shopid as brand, sum(qty_purchased) as quantity from shopee.income_item_detail as a inner join (select ordersn, shopid from shopee.order_transaction_shopee_naufal where pay_time is not null and shopid in (59763733, 63983008, 326487418) and order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) as b on a.ordersn = b.ordersn group by brand";
    String getTotalSoldItemEachMonthEachBrandQuery = "select brand, bulan, sum(qty_purchased) as quantity from shopee.income_item_detail as a inner join (select ordersn, shopid as brand, extract(MONTH from pay_time) as bulan from shopee.order_transaction_shopee_naufal where pay_time is not null and extract(YEAR from pay_time) = %d and shopid in (59763733, 63983008, 326487418) and order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) as b on a.ordersn = b.ordersn group by (brand, bulan) order by (brand, bulan)";
    String getTotalSoldItemEachYearEachBrandQuery = "select shopid as brand, extract(YEAR from pay_time) as tahun, sum(qty_purchased) as quantity from shopee.income_item_detail as a inner join (select ordersn, shopid, pay_time from shopee.order_transaction_shopee_naufal where pay_time is not null and shopid in (59763733, 63983008, 326487418) and order_status in ('READY_TO_SHIP', 'SHIPPED', 'COMPLETED', 'TO_CONFIRM_RECEIVE')) as b on a.ordersn = b.ordersn group by (brand, tahun) order by (tahun) asc";
}
